name: GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Stats Enhanced
        uses: hnrobert/github-stats-enhanced@v0.1.2
        with:
          github_user_name: Iosif00024
          github_token: ${{ secrets.PROFILE }}
          mode: all
